/* eslint-disable */
/**
 * Generated by Convex
 * This file is generated and should not be manually edited.
 */

const createApiProxy = () => {
  return new Proxy({}, {
    get: (target, prop) => {
      if (prop === '__esModule') return true;
      return createApiProxy();
    }
  });
};

export const api = createApiProxy();