/* eslint-disable */
/**
 * Generated by Convex
 * This file is generated and should not be manually edited.
 */
import { AnyDataModel } from "convex/server";
import type { DataModelDefinitionFromSchemaDefinition } from "convex/server";
import type { SchemaDefinition } from "convex/server";
import schema from "../schema.js";

type DataModelDefinition = DataModelDefinitionFromSchemaDefinition<
  SchemaDefinition<typeof schema, true>
>;

/**
 * The type of your data model.
 *
 * This type includes information about what tables you have, the type of their
 * documents, and the indexes on each table.
 */
export type DataModel = AnyDataModel & {
  __exports: {
    documentTypes: "activities" | "scheduledTasks" | "searchIndex";
    ids: {
      activities: string;
      scheduledTasks: string;
      searchIndex: string;
      _DocumentWithId: string;
    };
    definition: DataModelDefinition;
  };
};