/* eslint-disable */
/**
 * Generated by Convex
 * This file is generated and should not be manually edited.
 */
import type { DataModel } from "./dataModel.js";

/**
 * The names of all of your Convex documents.
 *
 * These document names are used as the generic parameters to `Table` in your
 * document types' `Id` types.
 */
export type TableNames = DataModel["__exports"]["documentTypes"];

/**
 * The type of a `Id` for a given document table.
 *
 * The generic parameter `TableName` should be the name of one of your Convex
 * documents, as provided to `Table` in your document schema. It defaults to
 * the string literal "_DocumentWithId" to prohibit use without a table name.
 *
 * @typeParam TableName - A string literal type naming one of your document types.
 */
export type Id<TableName extends TableNames = "_DocumentWithId"> =
  DataModel["__exports"]["ids"][TableName];

/**
 * A type describing your Convex data model.
 *
 * This type includes information about what tables you have, the type of their
 * documents, and the indexes on each table.
 */
export type DataModelDefinition = DataModel["__exports"]["definition"];