/* eslint-disable */
/**
 * Generated by Convex
 * This file is generated and should not be manually edited.
 */
export { query, mutation, action, internalQuery, internalMutation, internalAction, httpAction } from "convex/server";