/* eslint-disable */
/**
 * Generated by Convex
 * This file is generated and should not be manually edited.
 */
export { query, mutation, action, internalQuery, internalMutation, internalAction, httpAction, QueryCtx, MutationCtx, ActionCtx, DatabaseReader, DatabaseWriter, GenericDataModel, GenericActionCtx, } from "convex/server";